### PR TITLE
Fix Issue #2667

### PR DESCRIPTION
**Pull request by JTPetter**
fixes https://github.com/jasp-stats/jasp-test-release/issues/2667

### CODE REVIEW

**Comment by koenderks** [comment]
What does this fix?

**Comment by JTPetter** [comment]
Yes, I tested it! Thank you

**Comment by koenderks** [comment]
Hmm interesting, can you explain this fix to me? Doesn't !identical(samples, "") also have length > 1? Sorry if this is a weird question but I don't have my laptop and am curious :p

**Review by koenderks — APPROVED** [review]

**Comment by JTPetter** [comment]
Of course! "==" (or "!=") compares elements of an object element wise, so for instance entries in a vector one by one (but also matrices, dataframes etc.). So if your vector has length n it will return a boolean vector with length n. If you pass a boolean vector with length > 1 to a control statement in R, it will crash. I think this changed with R4.0, previously it would simply evaluate the first element of the boolean vector.

The identical function does a "deep" comparison, so it also checks whether the data type is the same. So the evaluated object will either be exactly an empty  *string* or FALSE. So the evaluation result is always a single boolean.

**Pull request merged**
