### PR TITLE
Translated to Turkish Language (%100) 

### PR DESCRIPTION
**Pull request by unalozden**
Translated 100% to Turkish by Ünal Halit Özden.

### CODE REVIEW

**Comment by shun2wang** [comment]
@unalozden Thanks for your contribution!❤ but we using [Weblate ](https://hosted.weblate.org/projects/jasp/)for collaboration, please refer to this translation [guideline](https://jasp-stats.org/translation-guidelines/) for more information.

Can you do this on Weblate if you have time?  for your current translated po file, you can also synchronize translation changes by uploading to weblate, refer to weblate [docs](https://docs.weblate.org/en/latest/user/files.html) for details, You can also translate other JASP modules on Weblate. with thanks.

**Comment by boutinb** [comment]
I have merged your changes, but as said @shun2wang, you should use WebLate, it's much more convenient!
Thanks for your work.

**Comment by shun2wang** [comment]
@boutinb but I saw Turkish language on Weblate had 98% translated  so this merge may overwrite some strings on it. I'm not sure if other collaborators of this language will be confused ...😉😉 I think the best way to do this is to upload this manually into Weblate so that some diff and history will be noticed.

**Comment by EJWagenmakers** [comment]
As an aside, it's great to have the Turkish translation for JASP!

**Comment by boutinb** [comment]
> @boutinb but I saw Turkish language on Weblate had 98% translated so this merge may overwrite some strings on it. I'm not sure if other collaborators of this language will be confused ...😉😉 I think the best way to do this is to upload this manually into Weblate so that some diff and history will be noticed.
> 
> EDIT: OK 98% already up to date. Nevermind.

I've checked in WebLate, the merge has only added translation, and not modified them. So I think it's OK.

**Comment by unalozden** [comment]
Thanks for your help.


Kimden: bruno boutin ***@***.***>
Yanıtla: jasp-stats/jaspLearnStats ***@***.***>
Tarih: 30 Ocak 2023 Pazartesi 14:59
Kime: jasp-stats/jaspLearnStats ***@***.***>
Bilgi: Unal Halit Ozden ***@***.***>, Mention ***@***.***>
Konu: Re: [jasp-stats/jaspLearnStats] Translated to Turkish Language (%100) (PR #25)


@boutinb<https://github.com/boutinb> but I saw Turkish language on Weblate had 98% translated so this merge may overwrite some strings on it. I'm not sure if other collaborators of this language will be confused ...😉😉 I think the best way to do this is to upload this manually into Weblate so that some diff and history will be noticed.

EDIT: OK 98% already up to date. Nevermind.

I've checked in WebLate, the merge has only added translation, and not modified them. So I think it's OK.

**Pull request merged**
