### PR TITLE
Mainly optical changes to descriptives

### PR DESCRIPTION
**Pull request by JTPetter**
Hope the commit messages are descriptive enough

### CODE REVIEW

**Comment by JTPetter** [comment]
@vandenman I see I actually have the right to merge without reviews. But I assume it's still preferable to do a review?

**Comment by vandenman** [comment]
> I see I actually have the right to merge without reviews.

@JTPetter that should be disabled now.

**Review by vandenman — APPROVED** [review]

**Comment by vandenman** [comment]
@JTPetter merge whenever you're ready!

**Comment by JTPetter** [comment]
@vandenman Thanks for approving! But I believe I also lost the right to merge: 
image

**Pull request merged**
